jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}
      - run: env | sort
      - run: make dev-lint
      - run: make lint-check
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}
      - run: env | sort
      - run: make dev-test
      - run: make test
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
